#!/usr/bin/env python3
"""Overnight autoresearch: iterate ternary boundary + width variants.

Runs autonomously: for each variant, edits train.py, trains, exports,
builds firmware, flashes, and reads on-device metrics. Results logged to TSV.

Usage:
    source /tmp/esp_auto_venv3/bin/activate
    python autoresearch/overnight_search.py [--dry-run] [--skip-flash]
"""

import argparse
import os
import re
import subprocess
import sys
import textwrap
import time
from datetime import datetime
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent
TRAIN_PY = Path(__file__).parent / "train.py"
RESULTS_TSV = Path(__file__).parent / "search_results.tsv"
ESP_PORT = os.environ.get("ESP_PORT", "/dev/cu.usbmodem5B414820541")
IDF_PATH = Path.home() / "Projects" / "esp-idf"
FIRMWARE_DIR = PROJECT_ROOT / "firmware"

# ---------------------------------------------------------------------------
# Variant definitions
# ---------------------------------------------------------------------------

VARIANTS = [
    {
        "name": "b-light_a025",
        "alpha": 0.25,
        "ternary_from_pw": 6,  # pw6-12 ternary, pw0-5 INT8
        "epochs": (15, 50, 15),
        "lr": 5e-4,
    },
    {
        "name": "b-heavy_a025",
        "alpha": 0.25,
        "ternary_from_pw": 8,  # pw8-12 ternary, pw0-7 INT8
        "epochs": (15, 50, 15),
        "lr": 5e-4,
    },
    {
        "name": "b-heavier_a025",
        "alpha": 0.25,
        "ternary_from_pw": 10,  # pw10-12 ternary, pw0-9 INT8
        "epochs": (15, 50, 15),
        "lr": 5e-4,
    },
    {
        "name": "all-int8_a025",
        "alpha": 0.25,
        "ternary_from_pw": 99,  # no ternary at all
        "epochs": (15, 50, 15),
        "lr": 5e-4,
    },
    {
        "name": "b-light_a030",
        "alpha": 0.30,
        "ternary_from_pw": 6,
        "epochs": (15, 50, 15),
        "lr": 5e-4,
    },
    {
        "name": "b-heavy_a030",
        "alpha": 0.30,
        "ternary_from_pw": 8,
        "epochs": (15, 50, 15),
        "lr": 5e-4,
    },
    {
        "name": "b-light_a020",
        "alpha": 0.20,
        "ternary_from_pw": 6,
        "epochs": (15, 50, 15),
        "lr": 5e-4,
    },
    {
        "name": "b-light_a025_longtrain",
        "alpha": 0.25,
        "ternary_from_pw": 6,
        "epochs": (20, 80, 20),  # longer training
        "lr": 3e-4,
    },
]


def get_pw_in_channels(alpha):
    """Return list of (block_idx, in_channels) for pointwise layers."""
    import torch.nn as nn
    sys.path.insert(0, str(PROJECT_ROOT / "model"))
    from train_baseline import MobileNetV1
    model = MobileNetV1(alpha=alpha, num_classes=2)
    pw_layers = []
    for i, block in enumerate(model.features):
        conv = block.pw[0]
        pw_layers.append((i, conv.in_channels))
    return pw_layers


def generate_train_py(variant):
    """Generate train.py content for a variant."""
    alpha = variant["alpha"]
    ternary_from = variant["ternary_from_pw"]
    epochs_w, epochs_t, epochs_f = variant["epochs"]
    lr = variant["lr"]

    pw_layers = get_pw_in_channels(alpha)
    n_blocks = len(pw_layers)

    # Build quant config
    lines = []
    lines.append(f'        "first_conv.0": "int8",')
    for i in range(n_blocks):
        lines.append(f'        "features.{i}.dw.0": "int8",')
    for i, (idx, in_c) in enumerate(pw_layers):
        mode = "ternary" if idx >= ternary_from else "int8"
        lines.append(f'        "features.{idx}.pw.0": "{mode}",')
    lines.append(f'        "classifier": "int8",')
    quant_config = "\n".join(lines)

    return textwrap.dedent(f'''\
        #!/usr/bin/env python3
        """Mutable target for autoresearch — auto-generated by overnight_search.py.
        Variant: {variant["name"]}
        """

        import sys
        from pathlib import Path
        sys.path.insert(0, str(Path(__file__).parent.parent / "model"))

        from train_baseline import MobileNetV1, DepthwiseSeparableConv


        def build_model():
            return MobileNetV1(alpha={alpha}, num_classes=2)


        def get_quant_config():
            return {{
        {quant_config}
            }}


        def get_hparams():
            return {{
                "lr": {lr},
                "wd": 1e-4,
                "epochs_warmup": {epochs_w},
                "epochs_ttq": {epochs_t},
                "epochs_freeze": {epochs_f},
                "batch_size": 64,
                "threshold_ratio": 0.05,
                "quant_config": get_quant_config(),
                "baseline_weights": "checkpoints/best_model.pt",
            }}
    ''')


def run_prepare(variant_name):
    """Run prepare.py (train + export + simulated verification). Returns (sim_acc, duration_s)."""
    print(f"\n{'='*60}")
    print(f"[search] Running prepare.py for: {variant_name}")
    print(f"{'='*60}")

    env = os.environ.copy()
    env["ESP_PORT"] = ""  # Don't try to flash during prepare
    env["PYTHONPATH"] = str(PROJECT_ROOT / "model")

    start = time.time()
    result = subprocess.run(
        [sys.executable, str(Path(__file__).parent / "prepare.py")],
        cwd=str(PROJECT_ROOT),
        capture_output=True,
        text=True,
        timeout=10800,  # 3 hours max
        env=env,
    )
    duration = time.time() - start

    print(result.stdout[-2000:] if len(result.stdout) > 2000 else result.stdout)
    if result.stderr:
        print(f"[search] STDERR: {result.stderr[-500:]}")

    # Parse simulated accuracy
    sim_acc = -1.0
    for line in result.stdout.splitlines():
        m = re.search(r"Verification accuracy: (\d+)/(\d+) = ([\d.]+)%", line)
        if m:
            sim_acc = float(m.group(3))
        m2 = re.search(r"Simulated INT8 accuracy: ([\d.]+)%", line)
        if m2:
            sim_acc = float(m2.group(1))

    # Parse float val accuracy
    float_acc = -1.0
    for line in result.stdout.splitlines():
        m = re.search(r"Best ternary val accuracy: ([\d.]+)", line)
        if m:
            float_acc = float(m.group(1)) * 100

    # Parse model size
    model_kb = -1.0
    for line in result.stdout.splitlines():
        m = re.search(r"([\d.]+) KB weights", line)
        if m:
            model_kb = float(m.group(1))

    return sim_acc, float_acc, model_kb, duration


def build_and_flash():
    """Build firmware and flash to ESP32. Returns True on success."""
    print(f"\n[search] Building and flashing firmware...")

    result = subprocess.run(
        ["bash", "-c",
         f"cd {IDF_PATH} && source export.sh 2>/dev/null && "
         f"cd {FIRMWARE_DIR} && "
         f"idf.py build 2>&1 && "
         f"idf.py -p {ESP_PORT} flash 2>&1"],
        capture_output=True,
        text=True,
        timeout=300,
    )

    if result.returncode != 0:
        print(f"[search] Build/flash FAILED: {result.stderr[-300:]}")
        return False

    print("[search] Build + flash OK")
    return True


def read_benchmark():
    """Send RUN_BENCHMARK to ESP32, parse METRIC line. Returns dict or None."""
    import serial

    try:
        ser = serial.Serial(ESP_PORT, 115200, timeout=2)
    except Exception as e:
        print(f"[search] Serial open failed: {e}")
        return None

    # Reset device
    ser.dtr = False
    time.sleep(0.1)
    ser.dtr = True
    time.sleep(4)

    # Flush boot messages
    while ser.in_waiting:
        ser.readline()

    # Send benchmark command
    ser.write(b"RUN_BENCHMARK\r\n")

    # Wait for METRIC line
    start = time.time()
    metric = None
    while time.time() - start < 120:
        line = ser.readline().decode("utf-8", errors="ignore").strip()
        m = re.match(r"METRIC\s+latency_us=(\d+)\s+accuracy=([\d.]+)\s+sram_free=(\d+)", line)
        if m:
            metric = {
                "latency_us": int(m.group(1)),
                "accuracy": float(m.group(2)),
                "sram_free": int(m.group(3)),
            }
            break

    ser.close()
    return metric


def log_result(variant_name, sim_acc, float_acc, model_kb, duration_s,
               device_acc, latency_us, sram_free):
    """Append result to TSV file."""
    header = "timestamp\tvariant\tfloat_acc\tsim_int8_acc\tdevice_acc\tlatency_ms\tsram_free\tmodel_kb\ttrain_time_min\n"
    if not RESULTS_TSV.exists():
        RESULTS_TSV.write_text(header)

    ts = datetime.now().strftime("%Y-%m-%d %H:%M")
    latency_ms = latency_us / 1000 if latency_us > 0 else -1
    train_min = duration_s / 60

    line = (f"{ts}\t{variant_name}\t{float_acc:.1f}\t{sim_acc:.1f}\t"
            f"{device_acc:.2f}\t{latency_ms:.1f}\t{sram_free}\t"
            f"{model_kb:.1f}\t{train_min:.1f}\n")

    with open(RESULTS_TSV, "a") as f:
        f.write(line)

    print(f"\n[search] === RESULT: {variant_name} ===")
    print(f"  Float accuracy:     {float_acc:.1f}%")
    print(f"  Simulated INT8:     {sim_acc:.1f}%")
    print(f"  On-device accuracy: {device_acc:.2f}")
    print(f"  Latency:            {latency_ms:.1f} ms")
    print(f"  SRAM free:          {sram_free}")
    print(f"  Model size:         {model_kb:.1f} KB")
    print(f"  Training time:      {train_min:.1f} min")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true",
                        help="Generate train.py for each variant but don't run")
    parser.add_argument("--skip-flash", action="store_true",
                        help="Skip build+flash, use simulated accuracy only")
    parser.add_argument("--variants", type=str, default=None,
                        help="Comma-separated variant names to run (default: all)")
    args = parser.parse_args()

    variants = VARIANTS
    if args.variants:
        names = set(args.variants.split(","))
        variants = [v for v in VARIANTS if v["name"] in names]
        if not variants:
            print(f"No matching variants. Available: {[v['name'] for v in VARIANTS]}")
            return

    print(f"[search] Running {len(variants)} variants")
    print(f"[search] Results will be logged to: {RESULTS_TSV}")
    print(f"[search] ESP port: {ESP_PORT}")
    print(f"[search] Skip flash: {args.skip_flash}")
    print()

    for i, variant in enumerate(variants):
        print(f"\n{'#'*60}")
        print(f"# Variant {i+1}/{len(variants)}: {variant['name']}")
        print(f"# Alpha={variant['alpha']} ternary_from_pw={variant['ternary_from_pw']}")
        print(f"# Epochs: {variant['epochs']}")
        print(f"{'#'*60}")

        # Generate train.py
        content = generate_train_py(variant)
        if args.dry_run:
            print(f"[dry-run] Would write train.py:\n{content[:500]}...")
            continue

        TRAIN_PY.write_text(content)
        print(f"[search] Wrote train.py for {variant['name']}")

        # Train + export
        sim_acc, float_acc, model_kb, duration = run_prepare(variant["name"])
        print(f"[search] Simulated INT8 accuracy: {sim_acc:.1f}%")
        print(f"[search] Float accuracy: {float_acc:.1f}%")
        print(f"[search] Training took {duration/60:.1f} min")

        # Build + flash + measure (unless skipped)
        device_acc = -1.0
        latency_us = -1
        sram_free = -1

        if not args.skip_flash and sim_acc >= 50.0:
            if build_and_flash():
                metric = read_benchmark()
                if metric:
                    device_acc = metric["accuracy"]
                    latency_us = metric["latency_us"]
                    sram_free = metric["sram_free"]
                else:
                    print("[search] WARNING: No METRIC from device")
            else:
                print("[search] WARNING: Build/flash failed")
        elif sim_acc < 50.0:
            print(f"[search] Skipping flash — simulated accuracy {sim_acc:.1f}% too low")

        # Log result
        log_result(variant["name"], sim_acc, float_acc, model_kb, duration,
                   device_acc, latency_us, sram_free)

    print(f"\n{'='*60}")
    print(f"[search] ALL DONE — {len(variants)} variants completed")
    print(f"[search] Results in: {RESULTS_TSV}")
    if RESULTS_TSV.exists():
        print(f"\n{RESULTS_TSV.read_text()}")


if __name__ == "__main__":
    main()
